name: Deploy to Test Folder (rsync)

on:
  push:
    branches: [ "**" ]   # cámbialo si usás otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rsync to server (test folder)
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avz --delete --exclude-from=".rsyncignore"
          path: ./
          remote_path: ${{ secrets.TARGET_DIR }}
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_port: ${{ secrets.SSH_PORT }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
